// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuopwmeqxcglxacmdtgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1b3B3bWVxeGNnbHhhY21kdGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjAzNTEsImV4cCI6MjA2ODU5NjM1MX0.J2z7c_z1Kj1L-w17XslhgbgcFKTz53TxA0k61dsR_CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});